# a = int(input("Ширина = "))
# b = int(input("Довжина = "))
# c = int(input("Висота = "))
# volume = float(a*b*c)
# print(volume)

exRate = float(input("курс = "))
sumCol = int(input("сума = "))
result = int((sumCol / 6500)/exRate)
print(result)
